<?php
class MyClass
{

    public $value = 'value-default';

    public $val = null;
    public $val1;

    /**
     * Var description.
     *
     * @var    integer
     * @since  1.0
     */
    public $valNum = 0;
    /**
     * Var description.
     *
     * @var    integer
     * @since  1.0
     */
    public $valNum1 = 0;

    public $val2;


    public $val3;
}

class MyClass
{



    /**
     * Var description.
     *
     * @var    integer
     * @since  1.0
     */
    public $value = 1;

    public $val = null;
    public $val1;
}
